// ✅ Define readable labels and icons for known attributes
const attributeMap: Record<string,{ label: string; iconURL: string, type:string }> = {
            'lactose_free': { type: 'dietary', iconURL: '/Icons/ColoredIcon/lactose-free.png' , label: 'Lactose-Free' },
            'vegan': { type: 'dietary', iconURL: '/Icons/ColoredIcon/vegan.png' , label: 'Vegan' },
            'gluten_free': { type: 'dietary', iconURL: '/Icons/ColoredIcon/gluten-free.png', label: 'Gluten-Free' },
            'made_with_millets': { type: 'ingredient', iconURL: '/Icons/ColoredIcon/millet.png' , label: 'Made with Millets' },
            'keto_friendly': { type: 'diet', iconURL: '/Icons/ColoredIcon/keto.png' , label: 'Keto-Friendly' },
            'diabetic_friendly': { type: 'health', iconURL: '/Icons/ColoredIcon/sugar-free.png', label: 'Diabetic-Friendly' },
            'pcos_friendly': { type: 'health', iconURL: '/Icons/ColoredIcon/PCSO.png' , label: 'PCOS-Friendly' },
            'no_preservatives': { type: 'clean', iconURL: '/Icons/ColoredIcon/no-preservatives.png' , label: 'No Preservatives' },
            'no_refined_flour': { type: 'clean', iconURL: '/Icons/ColoredIcon/refind-flour.png' , label: 'No Refined Flour' },
            'plant_based': { type: 'dietary', iconURL: '/Icons/ColoredIcon/Plant-Based.png', label: 'Plant-Based' },
            'high_protein': { type: 'nutrition', iconURL: '/Icons/ColoredIcon/high-protein.png' , label: 'High Protein' },
            'high_fiber': { type: 'nutrition', iconURL: '/Icons/ColoredIcon/high-fiber.png' , label: 'High Fiber' },
            'low_carb': { type: 'nutrition', iconURL: '/Icons/ColoredIcon/low-crab.png', label: 'Low Carb' },
            'low_gi': { type: 'health', iconURL: '/Icons/ColoredIcon/glycemic-index.png' , label: 'Low GI' },
            'soy_free': { type: 'allergen', iconURL: '/Icons/ColoredIcon/Soy Free.png' , label: 'Soy-Free' },
            'nut_free': { type: 'allergen', iconURL: '/Icons/ColoredIcon/nut.png' , label: 'Nut-Free' },
            'dairy_free': { type: 'allergen', iconURL: '/Icons/ColoredIcon/dairy-free.png' , label: 'Dairy-Free' },
            'egg_free': { type: 'allergen', iconURL: '/Icons/ColoredIcon/no-egg.png', label: 'Egg-Free' },
            'no_artificial_colors': { type: 'clean', iconURL: '/Icons/ColoredIcon/no-artificial-colours.png' , label: 'No Artificial Colors' },
            'no_artificial_flavors': { type: 'clean', iconURL: '/Icons/ColoredIcon/no-artificial-flavors.png' , label: 'No Artificial Flavors' },
            'non_gmo': { type: 'quality', iconURL: '/Icons/ColoredIcon/GMO.png', label: 'Non-GMO' },
            'organic_ingredients': { type: 'quality', iconURL: '/Icons/ColoredIcon/organic.png', label: 'Organic' },
            'whole_grain': { type: 'ingredient', iconURL: '/Icons/ColoredIcon/whole-wheat.png', label: 'Whole Grain' },
            'heart_healthy': { type: 'health', iconURL: '/Icons/ColoredIcon/heart-friendly.png' , label: 'Heart-Healthy' },
            'cholesterol_free': { type: 'health', iconURL: '/Icons/ColoredIcon/no-cholesterol.png' , label: 'Cholesterol-Free' },
            'trans_fat_free': { type: 'health', iconURL: '/Icons/ColoredIcon/trans-fat.png' , label: 'Trans-Fat-Free' },
            'zero_palm_oil': { type: 'environmental', iconURL: '/Icons/ColoredIcon/palm-oil-free.png', label: 'Zero Palm Oil' },
            'sustainable_ingredients': { type: 'environmental', iconURL: '/Icons/ColoredIcon/sustainability.png' , label: 'Sustainable' },
            'clean_label': { type: 'quality', iconURL: '/Icons/ColoredIcon/clean.png' , label: 'Clean Label' },
            'all_natural': { type: 'quality', iconURL: '/Icons/ColoredIcon/all-organic.png' , label: 'All Natural' },
            'yeast_free': { type: 'quality', iconURL: '/Icons/ColoredIcon/yeast_free.png' , label: 'Yeast Free' },
        };

        export default attributeMap